Theme PaperMod: update to latest
Also, fix mistake caused when running Hugo:

```
Error: error building site: process: readAndProcessContent: "/Users/cunnie/workspace/cunnie.github.io/content/post/nsx_tls.md:7:1": [6:1] mapping key "title" already defined at [1:1]
```