Resurrect old blog posts
...mostly so that I could update the procedure for getting a commercial
certificate for vCenter, vCenter 8 specifically.

Slight change `responsive-figure` → `figure` to fix:

```
Error: Error building site: "/Users/cunnie/workspace/cunnie.github.io/content/post/bosh-deployed-with-concourse.md:45:1": failed to extract shortcode: template for shortcode "responsive-figure" not found
```